FROM mongo:7.0

ENV MONGO_INITDB_ROOT_USERNAME=absent \
    MONGO_INITDB_ROOT_PASSWORD=CyMa2005! \
    MONGO_INITDB_DATABASE=absent

EXPOSE 27017

CMD ["mongod", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
